In [1]:
import torch
torch.__version__

'1.5.1+cpu'

In [2]:
x=torch.tensor(4.0)

In [3]:
print(x)
x.shape

tensor(4.)


torch.Size([])

###### Vector

In [4]:
x1=torch.tensor([1.,2,4.])

In [5]:
print(x1)
x1.shape

tensor([1., 2., 4.])


torch.Size([3])

###### Matrix

In [6]:
x2=torch.tensor([[1,2,3],[2,3,4]])

In [7]:
print(x2)
x2.shape

tensor([[1, 2, 3],
        [2, 3, 4]])


torch.Size([2, 3])

###### 3-D Matrix

In [8]:
x3=torch.tensor([
    [[2,3,4],[2,4,5]],
    [[1,2,3],[2,3,5]]
    ])

In [9]:
print(x3)
x3.shape

tensor([[[2, 3, 4],
         [2, 4, 5]],

        [[1, 2, 3],
         [2, 3, 5]]])


torch.Size([2, 2, 3])

###### Operations in Tensor

In [10]:
q = torch.tensor(4.,requires_grad=True)

In [11]:
y = q**2
print(y)

tensor(16., grad_fn=<PowBackward0>)


In [12]:
y.backward() # derivative function
print('dy/dq :', q.grad)# gradient

dy/dq : tensor(8.)
